### ISSUE TITLE
rails 5.2

### ISSUE THREAD

**Issue by ghost** [stevehodges/draftpunk#4]
I'm trying to install it on rails 5.2 but it won't let me, any chance you could allow it for rails 5.2 as well?

```terminal
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.2.0)

  In Gemfile:
    rails (~> 5.2.0)

    draft_punk (= 0.2.7) was resolved to 0.2.7, which depends on
      rails (< 5.1, > 3.0)
```

**Comment by ghost** [comment]
@stevehodges any status on this issue?

I'm trying to fork this gem, change and run the tests but my GEM knowledge is quite limited. Any tips where to start with that?

**Comment by stevehodges** [comment]
I'm planning to publish a 5.2 version of the gem today - thanks.

**Comment by stevehodges** [comment]
0.2.8 is available: https://rubygems.org/gems/draft_punk/versions/0.2.8
